30 improve markable position bb
fsparv/LeelaWatcher pull request #31
Opened 2018-01-26 19:40 UTC by barrybecker4

Made suggested changes and added unit tests.
Also replaced HashSet with Set in the interface.

2018-01-28 09:27 UTC, fsparv commented
conceptually this looks good. I'll need to pull it down, run the test with old/new code etc. I think I might be able to get to this and other pull requests later today (time for sleep now... or rather several hours ago :) ).

2018-01-29 02:19 UTC, fsparv requested changes
Seems good overall. If you make a couple minor tweaks noted below I'm happy to merge it.

2018-01-29 02:19 UTC, fsparv commented on src/test/java/leelawatcher/goboard/MarkablePositionTest.java
> +        pos.setMark(p1);
why set p1 twice?

2018-01-29 02:19 UTC, fsparv commented on src/test/java/leelawatcher/goboard/MarkablePositionTest.java
> +        pos.setMark(p1);
why set p1 twice here?

2018-01-29 02:21 UTC, fsparv commented on src/main/java/leelawatcher/goboard/MarkablePosition.java
> +  private void checkNbr(PointOfPlay p, int x, int y, Set<PointOfPlay> members, int boardSize) {
Please write out whatever Nbr stands for. I like long method names, my fingers will survive the typing but my brain might not survive the confusion... :)

2018-01-29 03:12 UTC, barrybecker4 commented
OK. Made the requested changes.

2018-02-01 03:10 UTC, merged